#!/usr/bin/env bash

red="\033[31m"
green="\033[0;32m"
magenta="\033[0;35m"
cyan="\033[0;36m"
white="\033[0;37m"
reset="\033[0m"

function cp_cnf_example() {
  local __root_dir=$1

  echo "Copying configuration files"
  for example in $(ls $__root_dir/Support/*.sample.plist); do
    local __without_example=${example/.sample/}
    echo -e "$green     $example $cyan ->> $magenta $__without_example"
    cp $example $__without_example
  done

  echo -e "$reset\c"

  return 0
}
